services:
  symfony:
    container_name: ${APP_PROJECT_NAME}_symfony
    image: wexample/php-8.2:latest
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN_MAIN}
    extends:
      file: ${SERVICE_DEFAULT_COMPOSE}
      service: default
