services:
  phpmyadmin:
    restart: unless-stopped
    container_name: ${APP_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      - PMA_HOST=${SERVICE_MYSQL_HOST}
      - PMA_PORT=${SERVICE_MYSQL_PORT}
    networks:
      - wex_net
